### ISSUE TITLE
graphics_fill_circle updates the value of global variable "i"

### ISSUE THREAD

**Issue by franc0is** [pebble/rockyjs#26]
Filing this to remember to look into it. See code at: https://jsbin.com/lasixih/3/edit?js,console,output

Declaring `i` with `var` in the for loop, or using a different variable name resolves the issue. Using `var` is probably good practice anyways, but I find it suspicious that our method would have this side effect.

**Comment by HBehrens** [comment]
You will find the reason for this in the erroneous implementation of `SAFE_HEAP_LOAD()` and `SAFE_HEAP_STORE()`. Both implementations use a global variable `i` for their iteration.

    function SAFE_HEAP_LOAD(a, b, c, d) {
        0 >= a && abort("segmentation fault loading " + b + " bytes from address " + a), a + b > Math.max(DYNAMICTOP, STATICTOP) && abort("segmentation fault, exceeded the top of the available heap when loading " + b + " bytes from address " + a + ". STATICTOP=" + STATICTOP + ", DYNAMICTOP=" + DYNAMICTOP), assert(TOTAL_MEMORY >= DYNAMICTOP);
        var e, f = getSafeHeapType(b, d);
        if (a % b !== 0)for (i = 0; i < b; i++)e |= HEAPU8[a + i >> 0] << 8 * i; else e = getValue(a, f, 1);
        return c && (e = unSign(e, parseInt(f.substr(1)), 1)), e
    }

    function SAFE_HEAP_STORE(a, b, c, d) {
        if (0 >= a && abort("segmentation fault storing " + c + " bytes to address " + a), a + c > Math.max(DYNAMICTOP, STATICTOP) && abort("segmentation fault, exceeded the top of the available heap when storing " + c + " bytes to address " + a + ". STATICTOP=" + STATICTOP + ", DYNAMICTOP=" + DYNAMICTOP), assert(TOTAL_MEMORY >= DYNAMICTOP), a % c !== 0)for (i = 0; i < c; i++)HEAPU8[a + i >> 0] = a >> 8 * i & 255; else setValue(a, b, getSafeHeapType(c, d), 1)
    }

If I see this correctly, it needs to be fixed during Rocky.js' transpiring processing.

**Comment by franc0is** [comment]
Filed PBL-32176 for tracking

**Comment by HBehrens** [comment]
Is this solved as part of 0.2.0?

**Comment by franc0is** [comment]
Yes, I just checked the bin.
