### ISSUE TITLE
i18n localization

### ISSUE THREAD

**Issue by orviwan** [pebble/rockyjs#28]
Perhaps something like https://github.com/jeresig/i18n-node-2

**Comment by HBehrens** [comment]
Are you proposing an example about how to combine Rocky.js with existing npm modules?

**Comment by orviwan** [comment]
I was unsure if you what your plans were for localization, but it sounds like you may already have something else in mind.

**Comment by HBehrens** [comment]
As you can see at the [section "Pebble API Compatibility" of Rocky's documentation](http://pebble.github.io/rockyjs/docs/) we are trying to embrace web standards. Many APIs that exist in our C-SDK do have a direct counterpart with standard Web APIs (e.g. battery) and won't be implemented as part of Rocky.js.

While i18n wasn't a direct part of our C-SDK we still think it's valuable to have this functionality for *some* applications. Having a way such as npm to share functionality as libraries makes sense to keep the memory footprint of a minimum application as low as possible. As you were referring to a library that can be integrated via npm, "Are you proposing an example about how to combine Rocky.js with existing npm modules?"

**Comment by orviwan** [comment]
Sure! Thanks for the feedback.
