### ISSUE TITLE
GColor

### ISSUE THREAD

**Issue by orviwan** [pebble/rockyjs#29]
I thought this library by @matthewtole might be useful. https://github.com/smallstoneapps/gcolor.js

**Comment by HBehrens** [comment]
The library looks great. What are you proposing, @orviwan? Writing a tutorial on how to embed it with Rocky.js?

**Comment by orviwan** [comment]
I thought this type of functionality would be part of the core offering, at least being able to use the color definitions within your code. GColor.Black etc.

**Comment by HBehrens** [comment]
We would like to keep the core as small as possible for obvious reasons. All color definitions as they exist in our C-Api are part of Rocky.js https://github.com/pebble/rockyjs/blob/master/src/symbols-generated.js#L90-L154 

With this in mind, "What are you proposing, @orviwan? Writing a tutorial on how to embed it with Rocky.js?"

**Comment by orviwan** [comment]
Ah, that makes sense. I didn't realise the colors were already available. I'll just keep this in mind for future implementations / examples.
