### ISSUE TITLE
move to up-to-date version of Node.js

### ISSUE THREAD

**Issue by HBehrens** [pebble/rockyjs#31]
Today, we use a [heavily outdated version of Node.js](https://github.com/pebble/rockyjs/blob/master/.travis.yml#L3), moving to an up-to-date version will give us some benefits.

- e.g. it might render the use of Q in `tasks/dist.js` unnecessary, related: [@sirlantis's hint in #30](https://github.com/pebble/rockyjs/pull/30#discussion_r50267302)

**Comment by franc0is** [comment]
Closed by https://github.com/pebble/rockyjs/pull/30
