### ISSUE TITLE
"Simply Square" example

### ISSUE THREAD

**Issue by NiVZ78** [pebble/rockyjs#35]
Sorry, I'm totally new to Git so wasn't sure what to do, but wondered if you'd consider adding my example:

http://jsbin.com/wakuha/15/edit?html,css,js,output

Thanks,

NiVZ

**Comment by ericmigi** [comment]
Nice demo! Giving @zalewszczak a run for the money on new JS faces :)

**Comment by HBehrens** [comment]
Also, @NiVZ78 there's already a PR #37 by @franc0is to add this to our examples. It will probably land shortly.

**Comment by franc0is** [comment]
Added in https://github.com/pebble/rockyjs/pull/37. Thanks @NiVZ78 !

**Comment by NiVZ78** [comment]
Thanks @ericmigi @heiko @franc0is 

Glad you all like it - I was very happy to see it on the wall in the SF Meetup video!  

I'm really impressed with everything you guys are doing.  RockyJS is great and really speeds up the my development process.  I've made another much more complicated one based on a real watch which you can see here:

http://jsbin.com/jokohi/edit?js,output

Thanks for adding Simply Squares to the community examples - hopefully it will encourage others to give it a try and share their designs.
