### ISSUE TITLE
Load resource (image, font) from different origin?

### ISSUE THREAD

**Issue by ygalanter** [pebble/rockyjs#70]
Trying to run code from one location (e.g. Jsbin) while loading bitmap/fonts from remote URL. Getting: 

XMLHttpRequest cannot load http://butkus.pebbledev.com/convert/image?url=http%3A%2F%2Fcodecorner.galan….net%2Fpebble%2Frockyjs%2Ffireplacejs%2Fresources%2Fimages%2Fframe-015.png. The 'Access-Control-Allow-Origin' header has a value **'http://codecorner.galanter.net'** that is not equal to the supplied origin. Origin **'http://null.jsbin.com'** is therefore not allowed access.

Any way around it?

**Comment by orviwan** [comment]
Have you tried just refreshing the browser window? I switched from the jsbin output to editing mode and I had the same issue.

**Comment by orviwan** [comment]
@ygalanter did this resolve the issue?

**Comment by ygalanter** [comment]
Sorry for delayed response, but unfortunately issue still there. If you take a look at this [jsbin](http://jsbin.com/bogalu/edit?html,js,output), bunch of errors in console are my own (canvas trying to load cross-origin image, but last one - I am trying to load font from my own site and also getting access denied error

**Comment by ygalanter** [comment]
I stand corrected. Apparently error happens only in Chrome, other browsers seem to let the font load. Still weird - any workaround for Chrome?

**Comment by ygalanter** [comment]
Never mind. I guess hosting matters too. When I linked directly from Git - it works!!! 
http://jsbin.com/bogalu/edit?html,js,output
